import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.scss";
import Providers from "./providers";

const notoSans = Noto_Sans({
  subsets: ["latin", "vietnamese"],
  weight: "variable",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className={`${notoSans.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
