networks:
  keepbin-net:
    name: keepbin-net
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_BACKEND_URL=https://api.${PROXY_DOMAIN}
    image: ngphuctoan/keepbin-frontend:dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=Host(`${PROXY_DOMAIN}`)||Host(`www.${PROXY_DOMAIN}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls=true
      # - traefik.http.routers.frontend.tls.certresolver=le
      - traefik.http.services.frontend.loadbalancer.server.port=80
    networks:
      - keepbin-net
    dns:
      - 10.0.10.20
    environment:
      - VITE_BACKEND_URL=https://api.${PROXY_DOMAIN}
    env_file:
      - path: ./frontend/.env
        required: false
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    restart: unless-stopped

  frontend-metrics:
    image: nginx/nginx-prometheus-exporter
    networks:
      - keepbin-net
    environment:
      - NGINX_SCRAPE_URI=http://frontend/stub_status
    restart: unless-stopped

  backend:
    build: ./backend
    image: ngphuctoan/keepbin-backend:dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=Host(`api.${PROXY_DOMAIN}`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls=true
      # - traefik.http.routers.backend.tls.certresolver=le
      - traefik.http.services.backend.loadbalancer.server.port=3000
    networks:
      - keepbin-net
    dns:
      - 10.0.10.20
    environment:
      - SESSION_SECRET=${BACKEND_SESSION_SECRET}
      - SESSION_REDIS_URL=redis://session:6379
      - CORS_ALLOWED_ORIGINS=["https://${PROXY_DOMAIN}"]
      - AUTH_ALLOWED_REDIRECTS=["https://${PROXY_DOMAIN}"]
      - DB_URL=postgres://postgres:${DB_PASS}@db:5432/postgres
      - S3_URL=http://s3:8333
      - S3_REGION=ap-southeast-1
      - S3_ACCESS_KEY_ID=admin
      - S3_ACCESS_KEY_SECRET=${S3_ACCESS_KEY_SECRET}
      - OID_ISSUER_BASE_URL=http://auth:8080/realms/keepbin/.well-known/openid-configuration
      - OID_CALLBACK_BASE_URL=https://api.${PROXY_DOMAIN}
      - OID_CLIENT_ID=backend
      - OID_CLIENT_SECRET=${OID_CLIENT_SECRET}
    env_file:
      - path: ./backend/.env
        required: false
    restart: unless-stopped

  db:
    image: postgres
    networks:
      - keepbin-net
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - db-data:/var/lib/postgresql:rw,Z
      - ./db/migrations:/docker-entrypoint-initdb.d:ro,Z
    restart: unless-stopped

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    networks:
      - keepbin-net
    environment:
      - DATA_SOURCE_URI=db:5432/postgres?sslmode=disable
      - DATA_SOURCE_USER=postgres
      - DATA_SOURCE_PASS=${DB_PASS}
    restart: unless-stopped

  s3:
    image: chrislusf/seaweedfs
    command: server -dir=/data -s3 -metricsPort=1234
    networks:
      - keepbin-net
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=${S3_ACCESS_KEY_SECRET}
    volumes:
      - s3-data:/data:rw,Z
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter
    networks:
      - keepbin-net
    environment:
      - REDIS_ADDR=redis://session:6379
    restart: unless-stopped

  seaweedfs-admin:
    image: chrislusf/seaweedfs
    command: |
      admin
        -adminUser=${SEAWEEDFS_ADMIN_USER} \
        -adminPassword=${SEAWEEDFS_ADMIN_PASS}
        -masters=s3:9333
    networks:
      - keepbin-net
    ports:
      - 23646:23646
    restart: unless-stopped

  auth:
    image: quay.io/keycloak/keycloak
    command: start-dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=Host(`auth.${PROXY_DOMAIN}`)
      - traefik.http.routers.auth.entrypoints=websecure
      - traefik.http.routers.auth.tls=true
      # - traefik.http.routers.auth.tls.certresolver=le
      - traefik.http.services.auth.loadbalancer.server.port=8080
    networks:
      - keepbin-net
    dns:
      - 10.0.10.20
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASS}
      - KC_HOSTNAME=https://auth.${PROXY_DOMAIN}
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    volumes:
      - auth-data:/opt/keycloak/data/h2:rw,Z
    restart: unless-stopped

  session:
    image: valkey/valkey
    networks:
      - keepbin-net
    restart: unless-stopped

  dns:
    image: coredns/coredns
    networks:
      keepbin-net:
        ipv4_address: 10.0.10.20
    ports:
      - 30053:53/tcp
      - 30053:53/udp
    volumes:
      - ./dns/zones:/zones:ro,Z
      - ./dns/Corefile:/Corefile:ro,Z
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter
    networks:
      - keepbin-net
    restart: unless-stopped

  prom:
    image: quay.io/prometheus/prometheus
    labels:
      - traefik.enable=true
      - traefik.http.routers.prom.rule=Host(`prom.${PROXY_DOMAIN}`)
      - traefik.http.routers.prom.entrypoints=websecure
      - traefik.http.routers.prom.tls=true
      # - traefik.http.routers.prom.tls.certresolver=le
      - traefik.http.services.prom.loadbalancer.server.port=9090
    networks:
      - keepbin-net
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.${PROXY_DOMAIN}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls=true
      # - traefik.http.routers.grafana.tls.certresolver=le
      - traefik.http.services.grafana.loadbalancer.server.port=3000
    networks:
      - keepbin-net
    volumes:
      - grafana-data:/var/lib/grafana:rw,Z
    restart: unless-stopped

  proxy:
    image: traefik:v3.6
    command:
      - --api.insecure=false
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=keepbin-net
      - --entrypoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --entryPoints.websecure.http.tls=true
      - --providers.file.directory=/dynamic
      # - --entryPoints.web.http.redirections.entryPoint.to=websecure
      # - --entryPoints.web.http.redirections.entryPoint.scheme=https
      # - --certificatesresolvers.le.acme.email=${LE_EMAIL}
      # - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      # - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
      - --metrics.prometheus=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.dashboard.rule=Host(`dashboard.${PROXY_DOMAIN}`)
      - traefik.http.routers.dashboard.entrypoints=websecure
      - traefik.http.routers.dashboard.service=api@internal
      - traefik.http.routers.dashboard.tls=true
    security_opt:
      - label=disable
      - no-new-privileges=true
    networks:
      keepbin-net:
        ipv4_address: 10.0.10.10
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./proxy/certs:/certs:ro
      - ./proxy/dynamic:/dynamic:ro
      - ./proxy/letsencrypt:/letsencrypt:rw
      - ${DOCKER_SOCKET}:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  db-data: {}
  s3-data: {}
  auth-data: {}
  grafana-data: {}
