networks:
  miniws-internal:
    name: miniws-internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.237.0.0/16

services:
  frontend-server:
    image: nginx:stable-alpine
    networks:
      miniws-internal:
        ipv4_address: 172.237.0.3
    ports:
      - 8080:80
    volumes:
      - ./01-frontend-server/html:/var/www/html:ro,Z
      - ./01-frontend-server/nginx.conf:/etc/nginx/nginx.conf:ro,Z
    restart: unless-stopped

  frontend-metrics-server:
    image: nginx/nginx-prometheus-exporter:latest
    networks:
      - miniws-internal
    ports:
      - 9113:9113
    environments:
      - NGINX_SCRAPE_URI=http://frontend-server/stub_status
    depends_on:
      - frontend-server
    restart: unless-stopped

  dns-server:
    image: ubuntu/bind9:latest
    networks:
      miniws-internal:
        ipv4_address: 172.237.0.2
    ports:
      - 30053:53/tcp
      - 30053:53/udp
    volumes:
      - ./06-dns-server:/etc/bind:ro,Z
    depends_on:
      - frontend-server
    restart: unless-stopped

  node-exporter-server:
    image: prom/node-exporter:latest
    networks:
      - miniws-internal
    ports:
      - 9100:9100
    restart: unless-stopped

  prometheus-server:
    image: prom/prometheus:latest
    networks:
      - miniws-internal
    ports:
      - 9090:9090
    volumes:
      - ./07-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro,Z
    depends_on:
      - node-exporter-server
      - frontend-metrics-server
    restart: unless-stopped
