import Header from "@/components/header";
import type { Metadata } from "next";
import "./globals.scss";
import { Container } from "react-bootstrap";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="d-flex flex-column vh-100">
        <Header />
        <Container className="flex-grow-1">{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
