events {}

http {
  server {
    listen 80;
    server_name miniws.internal www.miniws.internal;

    root /var/www/html;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }

    location = /stub_status {
      stub_status;
      allow 172.237.0.0/16;
      deny all;
    }
  }
}
