events {}

http {
  include mime.types;

  server {
    listen 80;
    server_name miniws.internal www.miniws.internal;

    root /var/www/html;

    location / {
      try_files $uri $uri.html $uri/ =404;
    }

    error_page 404 /404.html;
    location = /404.html {
      internal;
    }

    location = /stub_status {
      stub_status;
      allow 172.237.0.0/16;
      deny all;
    }
  }
}
