events {}

http {
  server {
    listen 80;
    server_name miniws.internal www.miniws.internal;

    root /var/www/html;
    index index.html;

    location / {
      try_files $uri $uri/ =404;
    }
  }
}
