options {
  directory "/var/cache/bind";

  // No forwarders, turn this into an authoritative server
  forwarders {};

  // DNS security validation ("auto" by default)
  dnssec-validation auto;

  // Only listens to this container address
  listen-on {
    172.237.0.2;
    127.0.0.1; // Fallback
  };

  // Only allow queries from container subnet
  allow-query {
    172.237.0.0/16;
  };

  // Enable recursion (on by default)
  recursion yes;
  // Only allow recursions from container subnet
  allow-recursion {
    172.237.0.0/16;
  };
};

zone "miniws.internal" {
  // Make this a master nameserver
  type master;
  file "/etc/bind/db.miniws.internal";
};
